[package]
name = "geolog"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.9"
ariadne = "0.4"  # for nice error reporting
uuid = { version = "1", features = ["v7"] }
roaring = "0.10"
nonminmax = "0.1"

[dev-dependencies]
insta = "1.40"  # snapshot testing
